name: Docker Image Serviceweb

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-serviceweb --tag urebal-serviceweb:1.0.63
      
    - name: Push to AWS ECR
      id: ecr
      uses: jwalton/gh-ecr-push@master
      with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: urebal-serviceweb:1.0.63
    
    - name: Install PostgreSQL Client
      run: |
        sudo apt update
        sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -yqq install libpq-dev postgresql-client-11
        
    - name: Run Scripts via psql
      env:
        PGHOST: ur-pg.cgytd5nannku.us-east-1.rds.amazonaws.com
        PGUSER: Github_Actions_DB
        PGPASSWORD: Github_Actions_DB
      run: |
        echo $(psql --version)
