name: Docker Image Serviceweb

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-serviceweb --tag urebal-serviceweb:1.0.63
      
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@master
      with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: urebal-serviceweb:1.0.63
